version: '3'

services:

  api:
    build: .
    image: dorin-university-backend
    command: npm run start-dev
    ports:
     - "8081:8081"
    volumes:
     - ./src:/srv/src

  db:
    image: "postgres:11.1"
    restart: always
    environment:
      POSTGRES_USER: dorin
      POSTGRES_PASSWORD: password