version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     #- run: BRANCH=$CIRCLE_BRANCH ./scripts/build.sh

     # run test
     - run: BRANCH=$CIRCLE_BRANCH ./scripts/test-ci.sh

     - store_artifacts:
        path: test-results
        destination: prefix

     - store_test_results:
        path: test-results


     # deploy the image
     #- run: docker push company/app:$CIRCLE_BRANCH