version: 2
jobs:
 build:
   machine: true
   working_directory: ~/src
   steps:
     - checkout

     # build the application image
     #- run: BRANCH=$CIRCLE_BRANCH ./scripts/build.sh

     # run test
     - run: BRANCH=$CIRCLE_BRANCH ./scripts/test-ci.sh

     - store_test_results:
        path: test-results

     - store_artifacts:
        path: ./test-results/mocha/results.xml
        destination: prefix


     # deploy the image
     #- run: docker push company/app:$CIRCLE_BRANCH